### ISSUE TITLE
InvalidPhpDocVarTagTypeRule: Parameter $checkMissingVarTagTypehint in __construct() has no class type hint or default value, so its value must be specified. 

### ISSUE THREAD

**Issue by Mte90** [szepeviktor/phpstan-phpdoc#2]
On https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/ I am getting this error
![Screenshot_20200525_185654](https://user-images.githubusercontent.com/403283/82831783-a3a72500-9eb9-11ea-8452-ea27970bc391.png)

**Comment by Mte90** [comment]
Adding this in arguments fix the issue
```checkMissingVarTagTypehint: %checkMissingVarTagTypehint%```

**Comment by szepeviktor** [comment]
Done :) in https://github.com/szepeviktor/phpstan-phpdoc/commit/d9c01d3fc83615653d1ac0a5b8677d022927bd34

Please confirm and I'll release v0.2.1

**Comment by Mte90** [comment]
```
        class: PHPStan\Rules\PhpDoc\InvalidPhpDocVarTagTypeRule
        arguments:
            checkClassCaseSensitivity: %checkClassCaseSensitivity%
            checkMissingVarTagTypehint: %checkMissingVarTagTypehint%
```
I added there the new line and now phpstan worked
